// DO NOT EDIT: File is generated by code generator.

import {
  Client,
  VERSION,
  Request,
  Method,
  Response,
  SendEcho,
  Echo,
  CreateOrganization,
  Organization,
  UpdateWebhook,
  CreateWebhook,
  OrganizationWorkerTaskWebhook,
  DeleteWebhook,
  ListWebhooks,
  PaginatedOrganizationWorkerTaskWebhook,
} from '../index';

import * as util from './util';

const client = new Client("~/.pokepay/test-config.ini");

test('simpleTest', async () => {
  const response: Echo = <Echo>(await client.send(new SendEcho({
    message: "Hello",
  }))).object;
  expect("ok").toBe(response.status);
  expect("Hello").toBe(response.message);
})
