# coding: utf-8
# DO NOT EDIT: File is generated by code generator.

import os
import unittest
import pokepay as pp
from pokepay.client import Client
import tests.util

package_root = os.path.dirname(os.path.dirname(pp.__file__))
config_path = os.path.join(package_root, 'config.ini')
client = Client(config_path)

def testCreateOrganization(self):
    code = "test-org" + tests.util.random_string(6)
    name = "テスト組織" + tests.util.random_string(4)
    private_money_ids = ["4b138a4c-8944-4f98-a5c4-96d3c1c415eb"]
    issuer_admin_user_email = "blackhole@pokepay.jp"
    member_admin_user_email = "blackhole@pokepay.jp"
    response = client.send(pp.CreateOrganization(
        code,
        name,
        private_money_ids,
        issuer_admin_user_email,
        member_admin_user_email
    ))
    self.assertEqual(code, response.code)
    self.assertEqual(name, response.name)
def testCreateOrganizationWithMetadata(self):
    code = "test-org" + tests.util.random_string(6)
    name = "テスト組織" + tests.util.random_string(4)
    private_money_ids = ["4b138a4c-8944-4f98-a5c4-96d3c1c415eb"]
    issuer_admin_user_email = "blackhole@pokepay.jp"
    member_admin_user_email = "blackhole@pokepay.jp"
    bank_code = "1234"
    bank_name = tests.util.random_string(4) + "銀行"
    bank_branch_code = "123"
    bank_branch_name = tests.util.random_string(4) + "支店"
    bank_account_type = "saving"
    bank_account = "1234567"
    bank_account_holder_name = "ﾌｸｻﾞﾜﾕｷﾁ"
    contact_name = "佐藤清"
    response = client.send(pp.CreateOrganization(
        code,
        name,
        private_money_ids,
        issuer_admin_user_email,
        member_admin_user_email,
        bank_code: bank_code,
        bank_name: bank_name,
        bank_branch_code: bank_branch_code,
        bank_branch_name: bank_branch_name,
        bank_account_type: bank_account_type,
        bank_account: bank_account,
        bank_account_holder_name: bank_account_holder_name,
        contact_name: contact_name
    ))
    self.assertEqual(code, response.code)
    self.assertEqual(name, response.name)
