# coding: utf-8
# DO NOT EDIT: File is generated by code generator.

import os
import unittest
import pokepay as pp
from pokepay.client import Client
import tests.util

package_root = os.path.dirname(os.path.dirname(pp.__file__))
config_path = os.path.join(package_root, 'config.ini')
client = Client(config_path)

def testCreateNewCustomerWithAccount(self):
    user_name = "user-name" + tests.util.random_string(6)
    account_name = "account-name" + tests.util.random_string(6)
    customer_account = client.send(pp.CreateCustomerAccount(
        "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
        user_name: user_name,
        account_name: account_name
    ))
    self.assertEqual(user_name, customer_account.user.name)
    self.assertEqual(account_name, customer_account.name)
    shop_name = "shop-name" + tests.util.random_string(6)
    shop = client.send(pp.CreateShopV2(
        shop_name,
        private_money_ids: ["4b138a4c-8944-4f98-a5c4-96d3c1c415eb"],
        can_topup_private_money_ids: ["4b138a4c-8944-4f98-a5c4-96d3c1c415eb"]
    ))
    topup_transaction = client.send(pp.CreateTopupTransaction(
        shop.id,
        customer_account.user.id,
        "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
        money_amount: 1000,
        point_amount: 1000
    ))
    self.assertEqual(topup_transaction.type, "topup")
    payment_transaction = client.send(pp.CreatePaymentTransaction(
        shop.id,
        customer_account.user.id,
        "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
        100
    ))
    bill = client.send(pp.CreateBill(
        "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
        shop.id
    ))
    bill_updated = client.send(pp.UpdateBill(
        bill.id,
        amount: 200.0
    ))
    bill_payment = client.send(pp.CreatePaymentTransactionWithBill(
        bill.id,
        customer_account.user.id
    ))
    self.assertEqual(payment_transaction.type, "payment")
    self.assertEqual(bill_payment.type, "payment")
    transactions = client.send(pp.ListTransactionsV2(private_money_id: "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
        shop_id: shop.id,
        customer_id: customer_account.user.id
    ))
    bill_transactions = client.send(pp.ListBillTransactions(private_money_id: "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
        shop_id: shop.id,
        customer_id: customer_account.user.id
    ))
    self.assertEqual(transactions.count, 3)
    self.assertEqual(bill_transactions.count, 1)
