# coding: utf-8
# DO NOT EDIT: File is generated by code generator.

import os
import unittest
import pokepay as pp
from pokepay.client import Client
import tests.util

package_root = os.path.dirname(os.path.dirname(pp.__file__))
config_path = os.path.join(package_root, 'config.ini')
client = Client(config_path)

def simple(self):
    response = client.send(pp.ListOrganizations(
        "4b138a4c-8944-4f98-a5c4-96d3c1c415eb"
    ))
    print(response)
def paging(self):
    response = client.send(pp.ListOrganizations(
        "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
        per_page: 3
    ))
    self.assertEqual(3, response.pagination.per_page)
