# coding: utf-8
# DO NOT EDIT: File is generated by code generator.

import os
import unittest
import pokepay as pp
from pokepay.client import Client
import tests.util

package_root = os.path.dirname(os.path.dirname(pp.__file__))
config_path = os.path.join(package_root, 'config.ini')
client = Client(config_path)

def testRegisterBankAccount(self):
    customer_name = "customer-name" + tests.util.random_string(6)
    account_name = "account-name" + tests.util.random_string(6)
    customer = client.send(pp.CreateCustomerAccount(
        "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
        user_name: customer_name,
        account_name: account_name
    ))
    user_device_metadata = "{\"user_agent\": \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0\"}"
    user_device = client.send(pp.CreateUserDevice(
        customer.user.id,
        metadata: user_device_metadata
    ))
    get_user_device_response = client.send(pp.GetUserDevice(
        user_device.id
    ))
    self.assertEqual(get_user_device_response.is_active, False)
    user_device_activated = client.send(pp.ActivateUserDevice(
        get_user_device_response.id
    ))
    self.assertEqual(user_device_activated.is_active, True)
    create_bank = client.send(pp.CreateBank(
        get_user_device_response.id,
        "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
        "dummy",
        "ポケペイタロウ"
    ))
    bank_accounts_listed = client.send(pp.ListBanks(
        get_user_device_response.id
    ))
    self.assertEqual(bank_accounts_listed.count, 0)
