# coding: utf-8
# DO NOT EDIT: File is generated by code generator.

import os
import unittest
import pokepay as pp
from pokepay.client import Client
import tests.util

package_root = os.path.dirname(os.path.dirname(pp.__file__))
config_path = os.path.join(package_root, 'config.ini')
client = Client(config_path)

def simpleTest(self):
    response = client.send(pp.SendEcho(
        "Hello"
    ))
    self.assertEqual("ok", response.status)
    self.assertEqual("Hello", response.message)
