// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { UserDevice } from "../response/UserDevice";

class ActivateUserDevice implements Request<UserDevice> {
  public readonly __r: UserDevice | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    user_device_id: string
  }) {
    if (params.user_device_id === void 0) throw new Error('"user_device_id" is required');
    this.path = "/user-devices" + "/" + params.user_device_id + "/activate";
    this.bodyParams = {};
  }
}

export { ActivateUserDevice };
