// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { BulkTransaction } from "../response/BulkTransaction";

class BulkCreateTransaction implements Request<BulkTransaction> {
  public readonly __r: BulkTransaction | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    name: string,
    description?: string,
    content: string,
    request_id: string,
    private_money_id?: string
  };
  public constructor(params: {
    name: string,
    description?: string,
    content: string,
    request_id: string,
    private_money_id?: string
  }) {
    if (params.name === void 0) throw new Error('"name" is required');
    if (params.content === void 0) throw new Error('"content" is required');
    if (params.request_id === void 0) throw new Error('"request_id" is required');
    this.path = "/transactions" + "/bulk";
    this.bodyParams = {
      name: params.name,
      content: params.content,
      request_id: params.request_id,
    };
    if (params.description !== void 0) this.bodyParams.description = params.description;
    if (params.private_money_id !== void 0) this.bodyParams.private_money_id = params.private_money_id;
  }
}

export { BulkCreateTransaction };
