// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { TransactionDetail } from "../response/TransactionDetail";

class CreateCpmTransaction implements Request<TransactionDetail> {
  public readonly __r: TransactionDetail | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    cpm_token: string,
    shop_id: string,
    amount: number,
    description?: string,
    metadata?: string,
    products?: Object[],
    request_id?: string
  };
  public constructor(params: {
    cpm_token: string,
    shop_id: string,
    amount: number,
    description?: string,
    metadata?: string,
    products?: Object[],
    request_id?: string
  }) {
    if (params.cpm_token === void 0) throw new Error('"cpm_token" is required');
    if (params.shop_id === void 0) throw new Error('"shop_id" is required');
    if (params.amount === void 0) throw new Error('"amount" is required');
    this.path = "/transactions" + "/cpm";
    this.bodyParams = {
      cpm_token: params.cpm_token,
      shop_id: params.shop_id,
      amount: params.amount,
    };
    if (params.description !== void 0) this.bodyParams.description = params.description;
    if (params.metadata !== void 0) this.bodyParams.metadata = params.metadata;
    if (params.products !== void 0) this.bodyParams.products = params.products;
    if (params.request_id !== void 0) this.bodyParams.request_id = params.request_id;
  }
}

export { CreateCpmTransaction };
