// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { TransactionDetail } from "../response/TransactionDetail";

class CreateBankTopupTransaction implements Request<TransactionDetail> {
  public readonly __r: TransactionDetail | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    private_money_id: string,
    amount: number,
    bank_id: string,
    request_id: string
  };
  public constructor(params: {
    user_device_id: string,
    private_money_id: string,
    amount: number,
    bank_id: string,
    request_id: string
  }) {
    if (params.user_device_id === void 0) throw new Error('"user_device_id" is required');
    if (params.private_money_id === void 0) throw new Error('"private_money_id" is required');
    if (params.amount === void 0) throw new Error('"amount" is required');
    if (params.bank_id === void 0) throw new Error('"bank_id" is required');
    if (params.request_id === void 0) throw new Error('"request_id" is required');
    this.path = "/user-devices" + "/" + params.user_device_id + "/banks" + "/topup";
    this.bodyParams = {
      private_money_id: params.private_money_id,
      amount: params.amount,
      bank_id: params.bank_id,
      request_id: params.request_id,
    };
  }
}

export { CreateBankTopupTransaction };
