// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { CouponDetail } from "../response/CouponDetail";

class CreateCoupon implements Request<CouponDetail> {
  public readonly __r: CouponDetail | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    private_money_id: string,
    name: string,
    description?: string,
    discount_amount?: number,
    discount_percentage?: number,
    discount_upper_limit?: number,
    starts_at: string,
    ends_at: string,
    display_starts_at?: string,
    display_ends_at?: string,
    is_disabled?: boolean,
    is_hidden?: boolean,
    is_public?: boolean,
    code?: string,
    usage_limit?: number,
    min_amount?: number,
    issued_shop_id: string,
    is_shop_specified?: boolean,
    available_shop_ids?: string[],
    storage_id?: string
  };
  public constructor(params: {
    private_money_id: string,
    name: string,
    description?: string,
    discount_amount?: number,
    discount_percentage?: number,
    discount_upper_limit?: number,
    starts_at: string,
    ends_at: string,
    display_starts_at?: string,
    display_ends_at?: string,
    is_disabled?: boolean,
    is_hidden?: boolean,
    is_public?: boolean,
    code?: string,
    usage_limit?: number,
    min_amount?: number,
    issued_shop_id: string,
    is_shop_specified?: boolean,
    available_shop_ids?: string[],
    storage_id?: string
  }) {
    if (params.private_money_id === void 0) throw new Error('"private_money_id" is required');
    if (params.name === void 0) throw new Error('"name" is required');
    if (params.starts_at === void 0) throw new Error('"starts_at" is required');
    if (params.ends_at === void 0) throw new Error('"ends_at" is required');
    if (params.issued_shop_id === void 0) throw new Error('"issued_shop_id" is required');
    this.path = "/coupons";
    this.bodyParams = {
      private_money_id: params.private_money_id,
      name: params.name,
      starts_at: params.starts_at,
      ends_at: params.ends_at,
      issued_shop_id: params.issued_shop_id,
    };
    if (params.description !== void 0) this.bodyParams.description = params.description;
    if (params.discount_amount !== void 0) this.bodyParams.discount_amount = params.discount_amount;
    if (params.discount_percentage !== void 0) this.bodyParams.discount_percentage = params.discount_percentage;
    if (params.discount_upper_limit !== void 0) this.bodyParams.discount_upper_limit = params.discount_upper_limit;
    if (params.display_starts_at !== void 0) this.bodyParams.display_starts_at = params.display_starts_at;
    if (params.display_ends_at !== void 0) this.bodyParams.display_ends_at = params.display_ends_at;
    if (params.is_disabled !== void 0) this.bodyParams.is_disabled = params.is_disabled;
    if (params.is_hidden !== void 0) this.bodyParams.is_hidden = params.is_hidden;
    if (params.is_public !== void 0) this.bodyParams.is_public = params.is_public;
    if (params.code !== void 0) this.bodyParams.code = params.code;
    if (params.usage_limit !== void 0) this.bodyParams.usage_limit = params.usage_limit;
    if (params.min_amount !== void 0) this.bodyParams.min_amount = params.min_amount;
    if (params.is_shop_specified !== void 0) this.bodyParams.is_shop_specified = params.is_shop_specified;
    if (params.available_shop_ids !== void 0) this.bodyParams.available_shop_ids = params.available_shop_ids;
    if (params.storage_id !== void 0) this.bodyParams.storage_id = params.storage_id;
  }
}

export { CreateCoupon };
