// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { OrganizationWorkerTaskWebhook } from "../response/OrganizationWorkerTaskWebhook";

class CreateWebhook implements Request<OrganizationWorkerTaskWebhook> {
  public readonly __r: OrganizationWorkerTaskWebhook | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    task: string,
    url: string
  };
  public constructor(params: {
    task: string,
    url: string
  }) {
    if (params.task === void 0) throw new Error('"task" is required');
    if (params.url === void 0) throw new Error('"url" is required');
    this.path = "/webhooks";
    this.bodyParams = {
      task: params.task,
      url: params.url,
    };
  }
}

export { CreateWebhook };
