// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { ShopWithAccounts } from "../response/ShopWithAccounts";

class CreateShopV2 implements Request<ShopWithAccounts> {
  public readonly __r: ShopWithAccounts | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    name: string,
    postal_code?: string,
    address?: string,
    tel?: string,
    email?: string,
    external_id?: string,
    organization_code?: string,
    private_money_ids?: string[],
    can_topup_private_money_ids?: string[]
  };
  public constructor(params: {
    name: string,
    postal_code?: string,
    address?: string,
    tel?: string,
    email?: string,
    external_id?: string,
    organization_code?: string,
    private_money_ids?: string[],
    can_topup_private_money_ids?: string[]
  }) {
    if (params.name === void 0) throw new Error('"name" is required');
    this.path = "/shops-v2";
    this.bodyParams = {
      name: params.name,
    };
    if (params.postal_code !== void 0) this.bodyParams.postal_code = params.postal_code;
    if (params.address !== void 0) this.bodyParams.address = params.address;
    if (params.tel !== void 0) this.bodyParams.tel = params.tel;
    if (params.email !== void 0) this.bodyParams.email = params.email;
    if (params.external_id !== void 0) this.bodyParams.external_id = params.external_id;
    if (params.organization_code !== void 0) this.bodyParams.organization_code = params.organization_code;
    if (params.private_money_ids !== void 0) this.bodyParams.private_money_ids = params.private_money_ids;
    if (params.can_topup_private_money_ids !== void 0) this.bodyParams.can_topup_private_money_ids = params.can_topup_private_money_ids;
  }
}

export { CreateShopV2 };
