// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { BankRegisteringInfo } from "../response/BankRegisteringInfo";

class CreateBank implements Request<BankRegisteringInfo> {
  public readonly __r: BankRegisteringInfo | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    private_money_id: string,
    callback_url: string,
    kana: string,
    email?: string,
    birthdate?: string
  };
  public constructor(params: {
    user_device_id: string,
    private_money_id: string,
    callback_url: string,
    kana: string,
    email?: string,
    birthdate?: string
  }) {
    if (params.user_device_id === void 0) throw new Error('"user_device_id" is required');
    if (params.private_money_id === void 0) throw new Error('"private_money_id" is required');
    if (params.callback_url === void 0) throw new Error('"callback_url" is required');
    if (params.kana === void 0) throw new Error('"kana" is required');
    this.path = "/user-devices" + "/" + params.user_device_id + "/banks";
    this.bodyParams = {
      private_money_id: params.private_money_id,
      callback_url: params.callback_url,
      kana: params.kana,
    };
    if (params.email !== void 0) this.bodyParams.email = params.email;
    if (params.birthdate !== void 0) this.bodyParams.birthdate = params.birthdate;
  }
}

export { CreateBank };
