// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { User } from "../response/User";

class CreateShop implements Request<User> {
  public readonly __r: User | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    shop_name: string,
    shop_postal_code?: string,
    shop_address?: string,
    shop_tel?: string,
    shop_email?: string,
    shop_external_id?: string,
    organization_code?: string
  };
  public constructor(params: {
    shop_name: string,
    shop_postal_code?: string,
    shop_address?: string,
    shop_tel?: string,
    shop_email?: string,
    shop_external_id?: string,
    organization_code?: string
  }) {
    if (params.shop_name === void 0) throw new Error('"shop_name" is required');
    this.path = "/shops";
    this.bodyParams = {
      shop_name: params.shop_name,
    };
    if (params.shop_postal_code !== void 0) this.bodyParams.shop_postal_code = params.shop_postal_code;
    if (params.shop_address !== void 0) this.bodyParams.shop_address = params.shop_address;
    if (params.shop_tel !== void 0) this.bodyParams.shop_tel = params.shop_tel;
    if (params.shop_email !== void 0) this.bodyParams.shop_email = params.shop_email;
    if (params.shop_external_id !== void 0) this.bodyParams.shop_external_id = params.shop_external_id;
    if (params.organization_code !== void 0) this.bodyParams.organization_code = params.organization_code;
  }
}

export { CreateShop };
