// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { UserDevice } from "../response/UserDevice";

class CreateUserDevice implements Request<UserDevice> {
  public readonly __r: UserDevice | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    user_id: string,
    metadata?: string
  };
  public constructor(params: {
    user_id: string,
    metadata?: string
  }) {
    if (params.user_id === void 0) throw new Error('"user_id" is required');
    this.path = "/user-devices";
    this.bodyParams = {
      user_id: params.user_id,
    };
    if (params.metadata !== void 0) this.bodyParams.metadata = params.metadata;
  }
}

export { CreateUserDevice };
