// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { TransactionDetail } from "../response/TransactionDetail";

class CreateTopupTransactionWithCheck implements Request<TransactionDetail> {
  public readonly __r: TransactionDetail | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    check_id: string,
    customer_id: string,
    request_id?: string
  };
  public constructor(params: {
    check_id: string,
    customer_id: string,
    request_id?: string
  }) {
    if (params.check_id === void 0) throw new Error('"check_id" is required');
    if (params.customer_id === void 0) throw new Error('"customer_id" is required');
    this.path = "/transactions" + "/topup" + "/check";
    this.bodyParams = {
      check_id: params.check_id,
      customer_id: params.customer_id,
    };
    if (params.request_id !== void 0) this.bodyParams.request_id = params.request_id;
  }
}

export { CreateTopupTransactionWithCheck };
