// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { AccountDeleted } from "../response/AccountDeleted";

class DeleteAccount implements Request<AccountDeleted> {
  public readonly __r: AccountDeleted | undefined;
  public readonly method: Method = "DELETE";
  public readonly path: string;
  public readonly bodyParams: {
    cashback?: boolean
  };
  public constructor(params: {
    account_id: string,
    cashback?: boolean
  }) {
    if (params.account_id === void 0) throw new Error('"account_id" is required');
    this.path = "/accounts" + "/" + params.account_id;
    this.bodyParams = {};
    if (params.cashback !== void 0) this.bodyParams.cashback = params.cashback;
  }
}

export { DeleteAccount };
