// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { BulkTransaction } from "../response/BulkTransaction";

class GetBulkTransaction implements Request<BulkTransaction> {
  public readonly __r: BulkTransaction | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    bulk_transaction_id: string
  }) {
    if (params.bulk_transaction_id === void 0) throw new Error('"bulk_transaction_id" is required');
    this.path = "/bulk-transactions" + "/" + params.bulk_transaction_id;
    this.bodyParams = {};
  }
}

export { GetBulkTransaction };
