// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Check } from "../response/Check";

class GetCheck implements Request<Check> {
  public readonly __r: Check | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    check_id: string
  }) {
    if (params.check_id === void 0) throw new Error('"check_id" is required');
    this.path = "/checks" + "/" + params.check_id;
    this.bodyParams = {};
  }
}

export { GetCheck };
