// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { CpmToken } from "../response/CpmToken";

class GetCpmToken implements Request<CpmToken> {
  public readonly __r: CpmToken | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    cpm_token: string
  }) {
    if (params.cpm_token === void 0) throw new Error('"cpm_token" is required');
    this.path = "/cpm" + "/" + params.cpm_token;
    this.bodyParams = {};
  }
}

export { GetCpmToken };
