// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { CouponDetail } from "../response/CouponDetail";

class GetCoupon implements Request<CouponDetail> {
  public readonly __r: CouponDetail | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    coupon_id: string
  }) {
    if (params.coupon_id === void 0) throw new Error('"coupon_id" is required');
    this.path = "/coupons" + "/" + params.coupon_id;
    this.bodyParams = {};
  }
}

export { GetCoupon };
