// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Campaign } from "../response/Campaign";

class GetCampaign implements Request<Campaign> {
  public readonly __r: Campaign | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    campaign_id: string
  }) {
    if (params.campaign_id === void 0) throw new Error('"campaign_id" is required');
    this.path = "/campaigns" + "/" + params.campaign_id;
    this.bodyParams = {};
  }
}

export { GetCampaign };
