// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { ExternalTransactionDetail } from "../response/ExternalTransactionDetail";

class GetExternalTransactionByRequestId implements Request<ExternalTransactionDetail> {
  public readonly __r: ExternalTransactionDetail | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    request_id: string
  }) {
    if (params.request_id === void 0) throw new Error('"request_id" is required');
    this.path = "/external-transactions" + "/requests" + "/" + params.request_id;
    this.bodyParams = {};
  }
}

export { GetExternalTransactionByRequestId };
