// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedPrivateMoneyOrganizationSummaries } from "../response/PaginatedPrivateMoneyOrganizationSummaries";

class GetPrivateMoneyOrganizationSummaries implements Request<PaginatedPrivateMoneyOrganizationSummaries> {
  public readonly __r: PaginatedPrivateMoneyOrganizationSummaries | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    from?: string,
    to?: string,
    page?: number,
    per_page?: number
  };
  public constructor(params: {
    private_money_id: string,
    from?: string,
    to?: string,
    page?: number,
    per_page?: number
  }) {
    if (params.private_money_id === void 0) throw new Error('"private_money_id" is required');
    this.path = "/private-moneys" + "/" + params.private_money_id + "/organization-summaries";
    this.bodyParams = {};
    if (params.from !== void 0) this.bodyParams.from = params.from;
    if (params.to !== void 0) this.bodyParams.to = params.to;
    if (params.page !== void 0) this.bodyParams.page = params.page;
    if (params.per_page !== void 0) this.bodyParams.per_page = params.per_page;
  }
}

export { GetPrivateMoneyOrganizationSummaries };
