// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PrivateMoneySummary } from "../response/PrivateMoneySummary";

class GetPrivateMoneySummary implements Request<PrivateMoneySummary> {
  public readonly __r: PrivateMoneySummary | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    from?: string,
    to?: string
  };
  public constructor(params: {
    private_money_id: string,
    from?: string,
    to?: string
  }) {
    if (params.private_money_id === void 0) throw new Error('"private_money_id" is required');
    this.path = "/private-moneys" + "/" + params.private_money_id + "/summary";
    this.bodyParams = {};
    if (params.from !== void 0) this.bodyParams.from = params.from;
    if (params.to !== void 0) this.bodyParams.to = params.to;
  }
}

export { GetPrivateMoneySummary };
