// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Pong } from "../response/Pong";

class GetPing implements Request<Pong> {
  public readonly __r: Pong | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params?: {}) {
    this.path = "/ping";
    this.bodyParams = {};
  }
}

export { GetPing };
