// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedPrivateMoneys } from "../response/PaginatedPrivateMoneys";

class GetPrivateMoneys implements Request<PaginatedPrivateMoneys> {
  public readonly __r: PaginatedPrivateMoneys | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    organization_code?: string,
    page?: number,
    per_page?: number
  };
  public constructor(params?: {
    organization_code?: string,
    page?: number,
    per_page?: number
  }) {
    this.path = "/private-moneys";
    this.bodyParams = {};
    if (params === void 0) return;
    if (params.organization_code !== void 0) this.bodyParams.organization_code = params.organization_code;
    if (params.page !== void 0) this.bodyParams.page = params.page;
    if (params.per_page !== void 0) this.bodyParams.per_page = params.per_page;
  }
}

export { GetPrivateMoneys };
