// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { TransactionDetail } from "../response/TransactionDetail";

class GetTransactionByRequestId implements Request<TransactionDetail> {
  public readonly __r: TransactionDetail | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    request_id: string
  }) {
    if (params.request_id === void 0) throw new Error('"request_id" is required');
    this.path = "/transactions" + "/requests" + "/" + params.request_id;
    this.bodyParams = {};
  }
}

export { GetTransactionByRequestId };
