// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { AdminUserWithShopsAndPrivateMoneys } from "../response/AdminUserWithShopsAndPrivateMoneys";

class GetUser implements Request<AdminUserWithShopsAndPrivateMoneys> {
  public readonly __r: AdminUserWithShopsAndPrivateMoneys | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params?: {}) {
    this.path = "/user";
    this.bodyParams = {};
  }
}

export { GetUser };
