// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedCoupons } from "../response/PaginatedCoupons";

class ListCoupons implements Request<PaginatedCoupons> {
  public readonly __r: PaginatedCoupons | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    private_money_id: string,
    coupon_id?: string,
    coupon_name?: string,
    issued_shop_name?: string,
    available_shop_name?: string,
    available_from?: string,
    available_to?: string,
    page?: number,
    per_page?: number
  };
  public constructor(params: {
    private_money_id: string,
    coupon_id?: string,
    coupon_name?: string,
    issued_shop_name?: string,
    available_shop_name?: string,
    available_from?: string,
    available_to?: string,
    page?: number,
    per_page?: number
  }) {
    if (params.private_money_id === void 0) throw new Error('"private_money_id" is required');
    this.path = "/coupons";
    this.bodyParams = {
      private_money_id: params.private_money_id,
    };
    if (params.coupon_id !== void 0) this.bodyParams.coupon_id = params.coupon_id;
    if (params.coupon_name !== void 0) this.bodyParams.coupon_name = params.coupon_name;
    if (params.issued_shop_name !== void 0) this.bodyParams.issued_shop_name = params.issued_shop_name;
    if (params.available_shop_name !== void 0) this.bodyParams.available_shop_name = params.available_shop_name;
    if (params.available_from !== void 0) this.bodyParams.available_from = params.available_from;
    if (params.available_to !== void 0) this.bodyParams.available_to = params.available_to;
    if (params.page !== void 0) this.bodyParams.page = params.page;
    if (params.per_page !== void 0) this.bodyParams.per_page = params.per_page;
  }
}

export { ListCoupons };
