// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedShops } from "../response/PaginatedShops";

class ListShops implements Request<PaginatedShops> {
  public readonly __r: PaginatedShops | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    organization_code?: string,
    private_money_id?: string,
    name?: string,
    postal_code?: string,
    address?: string,
    tel?: string,
    email?: string,
    external_id?: string,
    with_disabled?: boolean,
    page?: number,
    per_page?: number
  };
  public constructor(params?: {
    organization_code?: string,
    private_money_id?: string,
    name?: string,
    postal_code?: string,
    address?: string,
    tel?: string,
    email?: string,
    external_id?: string,
    with_disabled?: boolean,
    page?: number,
    per_page?: number
  }) {
    this.path = "/shops";
    this.bodyParams = {};
    if (params === void 0) return;
    if (params.organization_code !== void 0) this.bodyParams.organization_code = params.organization_code;
    if (params.private_money_id !== void 0) this.bodyParams.private_money_id = params.private_money_id;
    if (params.name !== void 0) this.bodyParams.name = params.name;
    if (params.postal_code !== void 0) this.bodyParams.postal_code = params.postal_code;
    if (params.address !== void 0) this.bodyParams.address = params.address;
    if (params.tel !== void 0) this.bodyParams.tel = params.tel;
    if (params.email !== void 0) this.bodyParams.email = params.email;
    if (params.external_id !== void 0) this.bodyParams.external_id = params.external_id;
    if (params.with_disabled !== void 0) this.bodyParams.with_disabled = params.with_disabled;
    if (params.page !== void 0) this.bodyParams.page = params.page;
    if (params.per_page !== void 0) this.bodyParams.per_page = params.per_page;
  }
}

export { ListShops };
