// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedBulkTransactionJob } from "../response/PaginatedBulkTransactionJob";

class ListBulkTransactionJobs implements Request<PaginatedBulkTransactionJob> {
  public readonly __r: PaginatedBulkTransactionJob | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    page?: number,
    per_page?: number
  };
  public constructor(params: {
    bulk_transaction_id: string,
    page?: number,
    per_page?: number
  }) {
    if (params.bulk_transaction_id === void 0) throw new Error('"bulk_transaction_id" is required');
    this.path = "/bulk-transactions" + "/" + params.bulk_transaction_id + "/jobs";
    this.bodyParams = {};
    if (params.page !== void 0) this.bodyParams.page = params.page;
    if (params.per_page !== void 0) this.bodyParams.per_page = params.per_page;
  }
}

export { ListBulkTransactionJobs };
