// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedTransfersV2 } from "../response/PaginatedTransfersV2";

class ListTransfersV2 implements Request<PaginatedTransfersV2> {
  public readonly __r: PaginatedTransfersV2 | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    shop_id?: string,
    shop_name?: string,
    customer_id?: string,
    customer_name?: string,
    transaction_id?: string,
    private_money_id?: string,
    is_modified?: boolean,
    transaction_types?: string[],
    next_page_cursor_id?: string,
    prev_page_cursor_id?: string,
    per_page?: number,
    transfer_types?: string[],
    description?: string,
    from?: string,
    to?: string
  };
  public constructor(params?: {
    shop_id?: string,
    shop_name?: string,
    customer_id?: string,
    customer_name?: string,
    transaction_id?: string,
    private_money_id?: string,
    is_modified?: boolean,
    transaction_types?: string[],
    next_page_cursor_id?: string,
    prev_page_cursor_id?: string,
    per_page?: number,
    transfer_types?: string[],
    description?: string,
    from?: string,
    to?: string
  }) {
    this.path = "/transfers-v2";
    this.bodyParams = {};
    if (params === void 0) return;
    if (params.shop_id !== void 0) this.bodyParams.shop_id = params.shop_id;
    if (params.shop_name !== void 0) this.bodyParams.shop_name = params.shop_name;
    if (params.customer_id !== void 0) this.bodyParams.customer_id = params.customer_id;
    if (params.customer_name !== void 0) this.bodyParams.customer_name = params.customer_name;
    if (params.transaction_id !== void 0) this.bodyParams.transaction_id = params.transaction_id;
    if (params.private_money_id !== void 0) this.bodyParams.private_money_id = params.private_money_id;
    if (params.is_modified !== void 0) this.bodyParams.is_modified = params.is_modified;
    if (params.transaction_types !== void 0) this.bodyParams.transaction_types = params.transaction_types;
    if (params.next_page_cursor_id !== void 0) this.bodyParams.next_page_cursor_id = params.next_page_cursor_id;
    if (params.prev_page_cursor_id !== void 0) this.bodyParams.prev_page_cursor_id = params.prev_page_cursor_id;
    if (params.per_page !== void 0) this.bodyParams.per_page = params.per_page;
    if (params.transfer_types !== void 0) this.bodyParams.transfer_types = params.transfer_types;
    if (params.description !== void 0) this.bodyParams.description = params.description;
    if (params.from !== void 0) this.bodyParams.from = params.from;
    if (params.to !== void 0) this.bodyParams.to = params.to;
  }
}

export { ListTransfersV2 };
