// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedChecks } from "../response/PaginatedChecks";

class ListChecks implements Request<PaginatedChecks> {
  public readonly __r: PaginatedChecks | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    page?: number,
    per_page?: number,
    private_money_id?: string,
    organization_code?: string,
    expires_from?: string,
    expires_to?: string,
    created_from?: string,
    created_to?: string,
    issuer_shop_id?: string,
    description?: string,
    is_onetime?: boolean,
    is_disabled?: boolean
  };
  public constructor(params?: {
    page?: number,
    per_page?: number,
    private_money_id?: string,
    organization_code?: string,
    expires_from?: string,
    expires_to?: string,
    created_from?: string,
    created_to?: string,
    issuer_shop_id?: string,
    description?: string,
    is_onetime?: boolean,
    is_disabled?: boolean
  }) {
    this.path = "/checks";
    this.bodyParams = {};
    if (params === void 0) return;
    if (params.page !== void 0) this.bodyParams.page = params.page;
    if (params.per_page !== void 0) this.bodyParams.per_page = params.per_page;
    if (params.private_money_id !== void 0) this.bodyParams.private_money_id = params.private_money_id;
    if (params.organization_code !== void 0) this.bodyParams.organization_code = params.organization_code;
    if (params.expires_from !== void 0) this.bodyParams.expires_from = params.expires_from;
    if (params.expires_to !== void 0) this.bodyParams.expires_to = params.expires_to;
    if (params.created_from !== void 0) this.bodyParams.created_from = params.created_from;
    if (params.created_to !== void 0) this.bodyParams.created_to = params.created_to;
    if (params.issuer_shop_id !== void 0) this.bodyParams.issuer_shop_id = params.issuer_shop_id;
    if (params.description !== void 0) this.bodyParams.description = params.description;
    if (params.is_onetime !== void 0) this.bodyParams.is_onetime = params.is_onetime;
    if (params.is_disabled !== void 0) this.bodyParams.is_disabled = params.is_disabled;
  }
}

export { ListChecks };
