// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Banks } from "../response/Banks";

class ListBanks implements Request<Banks> {
  public readonly __r: Banks | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    private_money_id?: string
  };
  public constructor(params: {
    user_device_id: string,
    private_money_id?: string
  }) {
    if (params.user_device_id === void 0) throw new Error('"user_device_id" is required');
    this.path = "/user-devices" + "/" + params.user_device_id + "/banks";
    this.bodyParams = {};
    if (params.private_money_id !== void 0) this.bodyParams.private_money_id = params.private_money_id;
  }
}

export { ListBanks };
