// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedOrganizationWorkerTaskWebhook } from "../response/PaginatedOrganizationWorkerTaskWebhook";

class ListWebhooks implements Request<PaginatedOrganizationWorkerTaskWebhook> {
  public readonly __r: PaginatedOrganizationWorkerTaskWebhook | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    page?: number,
    per_page?: number
  };
  public constructor(params?: {
    page?: number,
    per_page?: number
  }) {
    this.path = "/webhooks";
    this.bodyParams = {};
    if (params === void 0) return;
    if (params.page !== void 0) this.bodyParams.page = params.page;
    if (params.per_page !== void 0) this.bodyParams.per_page = params.per_page;
  }
}

export { ListWebhooks };
