// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedAccountDetails } from "../response/PaginatedAccountDetails";

class ListUserAccounts implements Request<PaginatedAccountDetails> {
  public readonly __r: PaginatedAccountDetails | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    page?: number,
    per_page?: number
  };
  public constructor(params: {
    user_id: string,
    page?: number,
    per_page?: number
  }) {
    if (params.user_id === void 0) throw new Error('"user_id" is required');
    this.path = "/users" + "/" + params.user_id + "/accounts";
    this.bodyParams = {};
    if (params.page !== void 0) this.bodyParams.page = params.page;
    if (params.per_page !== void 0) this.bodyParams.per_page = params.per_page;
  }
}

export { ListUserAccounts };
