// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { UserStatsOperation } from "../response/UserStatsOperation";

class RequestUserStats implements Request<UserStatsOperation> {
  public readonly __r: UserStatsOperation | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    from: string,
    to: string
  };
  public constructor(params: {
    from: string,
    to: string
  }) {
    if (params.from === void 0) throw new Error('"from" is required');
    if (params.to === void 0) throw new Error('"to" is required');
    this.path = "/user-stats";
    this.bodyParams = {
      from: params.from,
      to: params.to,
    };
  }
}

export { RequestUserStats };
