// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Echo } from "../response/Echo";

class SendEcho implements Request<Echo> {
  public readonly __r: Echo | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    message: string
  };
  public constructor(params: {
    message: string
  }) {
    if (params.message === void 0) throw new Error('"message" is required');
    this.path = "/echo";
    this.bodyParams = {
      message: params.message,
    };
  }
}

export { SendEcho };
