// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Bill } from "../response/Bill";

class UpdateBill implements Request<Bill> {
  public readonly __r: Bill | undefined;
  public readonly method: Method = "PATCH";
  public readonly path: string;
  public readonly bodyParams: {
    amount?: number,
    description?: string,
    is_disabled?: boolean
  };
  public constructor(params: {
    bill_id: string,
    amount?: number,
    description?: string,
    is_disabled?: boolean
  }) {
    if (params.bill_id === void 0) throw new Error('"bill_id" is required');
    this.path = "/bills" + "/" + params.bill_id;
    this.bodyParams = {};
    if (params.amount !== void 0) this.bodyParams.amount = params.amount;
    if (params.description !== void 0) this.bodyParams.description = params.description;
    if (params.is_disabled !== void 0) this.bodyParams.is_disabled = params.is_disabled;
  }
}

export { UpdateBill };
