// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { OrganizationWorkerTaskWebhook } from "../response/OrganizationWorkerTaskWebhook";

class UpdateWebhook implements Request<OrganizationWorkerTaskWebhook> {
  public readonly __r: OrganizationWorkerTaskWebhook | undefined;
  public readonly method: Method = "PATCH";
  public readonly path: string;
  public readonly bodyParams: {
    url?: string,
    is_active?: boolean,
    task?: string
  };
  public constructor(params: {
    webhook_id: string,
    url?: string,
    is_active?: boolean,
    task?: string
  }) {
    if (params.webhook_id === void 0) throw new Error('"webhook_id" is required');
    this.path = "/webhooks" + "/" + params.webhook_id;
    this.bodyParams = {};
    if (params.url !== void 0) this.bodyParams.url = params.url;
    if (params.is_active !== void 0) this.bodyParams.is_active = params.is_active;
    if (params.task !== void 0) this.bodyParams.task = params.task;
  }
}

export { UpdateWebhook };
