// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { AccountWithUser } from "../response/AccountWithUser";

class UpdateCustomerAccount implements Request<AccountWithUser> {
  public readonly __r: AccountWithUser | undefined;
  public readonly method: Method = "PATCH";
  public readonly path: string;
  public readonly bodyParams: {
    status?: string,
    account_name?: string,
    external_id?: string,
    metadata?: string
  };
  public constructor(params: {
    account_id: string,
    status?: string,
    account_name?: string,
    external_id?: string,
    metadata?: string
  }) {
    if (params.account_id === void 0) throw new Error('"account_id" is required');
    this.path = "/accounts" + "/" + params.account_id + "/customers";
    this.bodyParams = {};
    if (params.status !== void 0) this.bodyParams.status = params.status;
    if (params.account_name !== void 0) this.bodyParams.account_name = params.account_name;
    if (params.external_id !== void 0) this.bodyParams.external_id = params.external_id;
    if (params.metadata !== void 0) this.bodyParams.metadata = params.metadata;
  }
}

export { UpdateCustomerAccount };
