# DO NOT EDIT: File is generated by code generator.

from pokepay_partner_python_sdk.pokepay.response.response import PokepayResponse


class AccountBalance(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.expires_at = response_body['expires_at']
        self.money_amount = response_body['money_amount']
        self.point_amount = response_body['point_amount']

    def expires_at(self):
        return self.expires_at

    def money_amount(self):
        return self.money_amount

    def point_amount(self):
        return self.point_amount

