# DO NOT EDIT: File is generated by code generator.

from pokepay_partner_python_sdk.pokepay.response.response import PokepayResponse


class AccountWithUser(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.name = response_body['name']
        self.is_suspended = response_body['is_suspended']
        self.private_money = response_body['private_money']
        self.user = response_body['user']

    def id(self):
        return self.id

    def name(self):
        return self.name

    def is_suspended(self):
        return self.is_suspended

    def private_money(self):
        return self.private_money

    def user(self):
        return self.user

