# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class AccountTransferSummary(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.summaries = response_body['summaries']

    def summaries(self):
        return self.summaries

