# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class AccountDetail(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.name = response_body['name']
        self.is_suspended = response_body['is_suspended']
        self.balance = response_body['balance']
        self.money_balance = response_body['money_balance']
        self.point_balance = response_body['point_balance']
        self.private_money = response_body['private_money']

    def id(self):
        return self.id

    def name(self):
        return self.name

    def is_suspended(self):
        return self.is_suspended

    def balance(self):
        return self.balance

    def money_balance(self):
        return self.money_balance

    def point_balance(self):
        return self.point_balance

    def private_money(self):
        return self.private_money

