# DO NOT EDIT: File is generated by code generator.

from pokepay_partner_python_sdk.pokepay.response.response import PokepayResponse


class AdminUserWithShopsAndPrivateMoneys(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.role = response_body['role']
        self.email = response_body['email']
        self.name = response_body['name']
        self.is_active = response_body['is_active']
        self.organization = response_body['organization']
        self.shops = response_body['shops']
        self.private_moneys = response_body['private_moneys']

    def id(self):
        return self.id

    def role(self):
        return self.role

    def email(self):
        return self.email

    def name(self):
        return self.name

    def is_active(self):
        return self.is_active

    def organization(self):
        return self.organization

    def shops(self):
        return self.shops

    def private_moneys(self):
        return self.private_moneys

