# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class Bank(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.private_money = response_body['private_money']
        self.bank_name = response_body['bank_name']
        self.bank_code = response_body['bank_code']
        self.branch_number = response_body['branch_number']
        self.branch_name = response_body['branch_name']
        self.deposit_type = response_body['deposit_type']
        self.masked_account_number = response_body['masked_account_number']
        self.account_name = response_body['account_name']

    def id(self):
        return self.id

    def private_money(self):
        return self.private_money

    def bank_name(self):
        return self.bank_name

    def bank_code(self):
        return self.bank_code

    def branch_number(self):
        return self.branch_number

    def branch_name(self):
        return self.branch_name

    def deposit_type(self):
        return self.deposit_type

    def masked_account_number(self):
        return self.masked_account_number

    def account_name(self):
        return self.account_name

