# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class Banks(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.rows = response_body['rows']
        self.count = response_body['count']

    def rows(self):
        return self.rows

    def count(self):
        return self.count

