# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class BankRegisteringInfo(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.redirect_url = response_body['redirect_url']
        self.paytree_customer_number = response_body['paytree_customer_number']

    def redirect_url(self):
        return self.redirect_url

    def paytree_customer_number(self):
        return self.paytree_customer_number

