# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class BankDeleted(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        

    
