# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class Bill(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.amount = response_body['amount']
        self.max_amount = response_body['max_amount']
        self.min_amount = response_body['min_amount']
        self.description = response_body['description']
        self.account = response_body['account']
        self.is_disabled = response_body['is_disabled']
        self.token = response_body['token']

    def id(self):
        return self.id

    def amount(self):
        return self.amount

    def max_amount(self):
        return self.max_amount

    def min_amount(self):
        return self.min_amount

    def description(self):
        return self.description

    def account(self):
        return self.account

    def is_disabled(self):
        return self.is_disabled

    def token(self):
        return self.token

