# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class BillTransaction(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.transaction = response_body['transaction']
        self.bill = response_body['bill']

    def transaction(self):
        return self.transaction

    def bill(self):
        return self.bill

