# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class Campaign(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.name = response_body['name']
        self.applicable_shops = response_body['applicable_shops']
        self.is_exclusive = response_body['is_exclusive']
        self.starts_at = response_body['starts_at']
        self.ends_at = response_body['ends_at']
        self.point_expires_at = response_body['point_expires_at']
        self.point_expires_in_days = response_body['point_expires_in_days']
        self.priority = response_body['priority']
        self.description = response_body['description']
        self.bear_point_shop = response_body['bear_point_shop']
        self.private_money = response_body['private_money']
        self.dest_private_money = response_body['dest_private_money']
        self.max_total_point_amount = response_body['max_total_point_amount']
        self.point_calculation_rule = response_body['point_calculation_rule']
        self.point_calculation_rule_object = response_body['point_calculation_rule_object']
        self.status = response_body['status']
        self.budget_caps_amount = response_body['budget_caps_amount']
        self.budget_current_amount = response_body['budget_current_amount']
        self.budget_current_time = response_body['budget_current_time']

    def id(self):
        return self.id

    def name(self):
        return self.name

    def applicable_shops(self):
        return self.applicable_shops

    def is_exclusive(self):
        return self.is_exclusive

    def starts_at(self):
        return self.starts_at

    def ends_at(self):
        return self.ends_at

    def point_expires_at(self):
        return self.point_expires_at

    def point_expires_in_days(self):
        return self.point_expires_in_days

    def priority(self):
        return self.priority

    def description(self):
        return self.description

    def bear_point_shop(self):
        return self.bear_point_shop

    def private_money(self):
        return self.private_money

    def dest_private_money(self):
        return self.dest_private_money

    def max_total_point_amount(self):
        return self.max_total_point_amount

    def point_calculation_rule(self):
        return self.point_calculation_rule

    def point_calculation_rule_object(self):
        return self.point_calculation_rule_object

    def status(self):
        return self.status

    def budget_caps_amount(self):
        return self.budget_caps_amount

    def budget_current_amount(self):
        return self.budget_current_amount

    def budget_current_time(self):
        return self.budget_current_time

