# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class CampaignShopLabelUserTagGroup(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.name_en = response_body['name_en']
        self.name_ja = response_body['name_ja']

    def id(self):
        return self.id

    def name_en(self):
        return self.name_en

    def name_ja(self):
        return self.name_ja

