# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class CapturedCreditSession(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.session_id = response_body['session_id']

    def session_id(self):
        return self.session_id

