# DO NOT EDIT: File is generated by code generator.

from pokepay_partner_python_sdk.pokepay.response.response import PokepayResponse


class Cashtray(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.amount = response_body['amount']
        self.description = response_body['description']
        self.account = response_body['account']
        self.expires_at = response_body['expires_at']
        self.canceled_at = response_body['canceled_at']
        self.token = response_body['token']

    def id(self):
        return self.id

    def amount(self):
        return self.amount

    def description(self):
        return self.description

    def account(self):
        return self.account

    def expires_at(self):
        return self.expires_at

    def canceled_at(self):
        return self.canceled_at

    def token(self):
        return self.token

