# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class CashtrayAttempt(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.account = response_body['account']
        self.status_code = response_body['status_code']
        self.error_type = response_body['error_type']
        self.error_message = response_body['error_message']
        self.created_at = response_body['created_at']

    def account(self):
        return self.account

    def status_code(self):
        return self.status_code

    def error_type(self):
        return self.error_type

    def error_message(self):
        return self.error_message

    def created_at(self):
        return self.created_at

