# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class CouponDetail(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.name = response_body['name']
        self.issued_shop = response_body['issued_shop']
        self.description = response_body['description']
        self.discount_amount = response_body['discount_amount']
        self.discount_percentage = response_body['discount_percentage']
        self.discount_upper_limit = response_body['discount_upper_limit']
        self.starts_at = response_body['starts_at']
        self.ends_at = response_body['ends_at']
        self.display_starts_at = response_body['display_starts_at']
        self.display_ends_at = response_body['display_ends_at']
        self.usage_limit = response_body['usage_limit']
        self.min_amount = response_body['min_amount']
        self.is_shop_specified = response_body['is_shop_specified']
        self.is_hidden = response_body['is_hidden']
        self.is_public = response_body['is_public']
        self.code = response_body['code']
        self.is_disabled = response_body['is_disabled']
        self.token = response_body['token']
        self.coupon_image = response_body['coupon_image']
        self.available_shops = response_body['available_shops']
        self.private_money = response_body['private_money']

    def id(self):
        return self.id

    def name(self):
        return self.name

    def issued_shop(self):
        return self.issued_shop

    def description(self):
        return self.description

    def discount_amount(self):
        return self.discount_amount

    def discount_percentage(self):
        return self.discount_percentage

    def discount_upper_limit(self):
        return self.discount_upper_limit

    def starts_at(self):
        return self.starts_at

    def ends_at(self):
        return self.ends_at

    def display_starts_at(self):
        return self.display_starts_at

    def display_ends_at(self):
        return self.display_ends_at

    def usage_limit(self):
        return self.usage_limit

    def min_amount(self):
        return self.min_amount

    def is_shop_specified(self):
        return self.is_shop_specified

    def is_hidden(self):
        return self.is_hidden

    def is_public(self):
        return self.is_public

    def code(self):
        return self.code

    def is_disabled(self):
        return self.is_disabled

    def token(self):
        return self.token

    def coupon_image(self):
        return self.coupon_image

    def available_shops(self):
        return self.available_shops

    def private_money(self):
        return self.private_money

