# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class CpmToken(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.cpm_token = response_body['cpm_token']
        self.account = response_body['account']
        self.transaction = response_body['transaction']
        self.event = response_body['event']
        self.scopes = response_body['scopes']
        self.expires_at = response_body['expires_at']
        self.metadata = response_body['metadata']

    def cpm_token(self):
        return self.cpm_token

    def account(self):
        return self.account

    def transaction(self):
        return self.transaction

    def event(self):
        return self.event

    def scopes(self):
        return self.scopes

    def expires_at(self):
        return self.expires_at

    def metadata(self):
        return self.metadata

