# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class CreditSession(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.expires_at = response_body['expires_at']

    def id(self):
        return self.id

    def expires_at(self):
        return self.expires_at

