# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class CustomerListRow(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.name = response_body['name']
        self.tel = response_body['tel']
        self.email = response_body['email']
        self.registered_at = response_body['registered_at']
        self.last_transaction_done_at = response_body['last_transaction_done_at']
        self.money_balance = response_body['money_balance']
        self.point_balance = response_body['point_balance']
        self.account_uuid = response_body['account_uuid']
        self.account_is_suspended = response_body['account_is_suspended']
        self.account_status = response_body['account_status']
        self.external_id = response_body['external_id']
        self.individual_number_identification = response_body['individual_number_identification']

    def id(self):
        return self.id

    def name(self):
        return self.name

    def tel(self):
        return self.tel

    def email(self):
        return self.email

    def registered_at(self):
        return self.registered_at

    def last_transaction_done_at(self):
        return self.last_transaction_done_at

    def money_balance(self):
        return self.money_balance

    def point_balance(self):
        return self.point_balance

    def account_uuid(self):
        return self.account_uuid

    def account_is_suspended(self):
        return self.account_is_suspended

    def account_status(self):
        return self.account_status

    def external_id(self):
        return self.external_id

    def individual_number_identification(self):
        return self.individual_number_identification

