# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class CvsAuthorization(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.account = response_body['account']
        self.user = response_body['user']
        self.order_id = response_body['order_id']
        self.transaction_id = response_body['transaction_id']
        self.pay_limit = response_body['pay_limit']
        self.tel = response_body['tel']
        self.name1 = response_body['name1']
        self.name2 = response_body['name2']
        self.amount = response_body['amount']
        self.service_option_type = response_body['service_option_type']
        self.haraikomi_url = response_body['haraikomi_url']
        self.receipt_no = response_body['receipt_no']
        self.done_at = response_body['done_at']
        self.canceled_at = response_body['canceled_at']

    def account(self):
        return self.account

    def user(self):
        return self.user

    def order_id(self):
        return self.order_id

    def transaction_id(self):
        return self.transaction_id

    def pay_limit(self):
        return self.pay_limit

    def tel(self):
        return self.tel

    def name1(self):
        return self.name1

    def name2(self):
        return self.name2

    def amount(self):
        return self.amount

    def service_option_type(self):
        return self.service_option_type

    def haraikomi_url(self):
        return self.haraikomi_url

    def receipt_no(self):
        return self.receipt_no

    def done_at(self):
        return self.done_at

    def canceled_at(self):
        return self.canceled_at

