# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class IndividualNumberIdentification(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.is_identified = response_body['is_identified']
        self.last_identified_at = response_body['last_identified_at']
        self.expires_at = response_body['expires_at']
        self.is_resident = response_body['is_resident']

    def is_identified(self):
        return self.is_identified

    def last_identified_at(self):
        return self.last_identified_at

    def expires_at(self):
        return self.expires_at

    def is_resident(self):
        return self.is_resident

