# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class OrganizationWorkerTaskWebhook(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.organization_code = response_body['organization_code']
        self.task = response_body['task']
        self.url = response_body['url']
        self.content_type = response_body['content_type']
        self.is_active = response_body['is_active']

    def id(self):
        return self.id

    def organization_code(self):
        return self.organization_code

    def task(self):
        return self.task

    def url(self):
        return self.url

    def content_type(self):
        return self.content_type

    def is_active(self):
        return self.is_active

