# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class PaginatedCvsAuthorizations(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.per_page = response_body['per_page']
        self.count = response_body['count']
        self.items = response_body['items']
        self.prev = response_body['prev']
        self.next = response_body['next']

    def per_page(self):
        return self.per_page

    def count(self):
        return self.count

    def items(self):
        return self.items

    def prev(self):
        return self.prev

    def next(self):
        return self.next

