# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class Pagination(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.current = response_body['current']
        self.per_page = response_body['per_page']
        self.max_page = response_body['max_page']
        self.has_prev = response_body['has_prev']
        self.has_next = response_body['has_next']

    def current(self):
        return self.current

    def per_page(self):
        return self.per_page

    def max_page(self):
        return self.max_page

    def has_prev(self):
        return self.has_prev

    def has_next(self):
        return self.has_next

