# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class PaginatedBillTransaction(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.rows = response_body['rows']
        self.per_page = response_body['per_page']
        self.count = response_body['count']
        self.next_page_cursor_id = response_body['next_page_cursor_id']
        self.prev_page_cursor_id = response_body['prev_page_cursor_id']

    def rows(self):
        return self.rows

    def per_page(self):
        return self.per_page

    def count(self):
        return self.count

    def next_page_cursor_id(self):
        return self.next_page_cursor_id

    def prev_page_cursor_id(self):
        return self.prev_page_cursor_id

