# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class Pong(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.pong = response_body['pong']

    def pong(self):
        return self.pong

