# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class PrivateMoneySummary(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.topup_amount = response_body['topup_amount']
        self.refunded_topup_amount = response_body['refunded_topup_amount']
        self.payment_amount = response_body['payment_amount']
        self.refunded_payment_amount = response_body['refunded_payment_amount']
        self.added_point_amount = response_body['added_point_amount']
        self.topup_point_amount = response_body['topup_point_amount']
        self.campaign_point_amount = response_body['campaign_point_amount']
        self.refunded_added_point_amount = response_body['refunded_added_point_amount']
        self.exchange_inflow_amount = response_body['exchange_inflow_amount']
        self.exchange_outflow_amount = response_body['exchange_outflow_amount']
        self.transaction_count = response_body['transaction_count']

    def topup_amount(self):
        return self.topup_amount

    def refunded_topup_amount(self):
        return self.refunded_topup_amount

    def payment_amount(self):
        return self.payment_amount

    def refunded_payment_amount(self):
        return self.refunded_payment_amount

    def added_point_amount(self):
        return self.added_point_amount

    def topup_point_amount(self):
        return self.topup_point_amount

    def campaign_point_amount(self):
        return self.campaign_point_amount

    def refunded_added_point_amount(self):
        return self.refunded_added_point_amount

    def exchange_inflow_amount(self):
        return self.exchange_inflow_amount

    def exchange_outflow_amount(self):
        return self.exchange_outflow_amount

    def transaction_count(self):
        return self.transaction_count

