# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class Product(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.jan_code = response_body['jan_code']
        self.name = response_body['name']
        self.unit_price = response_body['unit_price']
        self.price = response_body['price']
        self.quantity = response_body['quantity']
        self.is_discounted = response_body['is_discounted']
        self.other = response_body['other']

    def jan_code(self):
        return self.jan_code

    def name(self):
        return self.name

    def unit_price(self):
        return self.unit_price

    def price(self):
        return self.price

    def quantity(self):
        return self.quantity

    def is_discounted(self):
        return self.is_discounted

    def other(self):
        return self.other

