# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class SevenBankATMSession(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.qr_info = response_body['qr_info']
        self.account = response_body['account']
        self.amount = response_body['amount']
        self.transaction = response_body['transaction']
        self.seven_bank_customer_number = response_body['seven_bank_customer_number']
        self.atm_id = response_body['atm_id']
        self.audi_id = response_body['audi_id']
        self.issuer_code = response_body['issuer_code']
        self.issuer_name = response_body['issuer_name']
        self.money_name = response_body['money_name']

    def qr_info(self):
        return self.qr_info

    def account(self):
        return self.account

    def amount(self):
        return self.amount

    def transaction(self):
        return self.transaction

    def seven_bank_customer_number(self):
        return self.seven_bank_customer_number

    def atm_id(self):
        return self.atm_id

    def audi_id(self):
        return self.audi_id

    def issuer_code(self):
        return self.issuer_code

    def issuer_name(self):
        return self.issuer_name

    def money_name(self):
        return self.money_name

