# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class ShopWithMetadata(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.name = response_body['name']
        self.organization_code = response_body['organization_code']
        self.status = response_body['status']
        self.postal_code = response_body['postal_code']
        self.address = response_body['address']
        self.tel = response_body['tel']
        self.email = response_body['email']
        self.external_id = response_body['external_id']

    def id(self):
        return self.id

    def name(self):
        return self.name

    def organization_code(self):
        return self.organization_code

    def status(self):
        return self.status

    def postal_code(self):
        return self.postal_code

    def address(self):
        return self.address

    def tel(self):
        return self.tel

    def email(self):
        return self.email

    def external_id(self):
        return self.external_id

