# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class TransactionGroup(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.name = response_body['name']
        self.created_at = response_body['created_at']
        self.updated_at = response_body['updated_at']
        self.transactions = response_body['transactions']

    def id(self):
        return self.id

    def name(self):
        return self.name

    def created_at(self):
        return self.created_at

    def updated_at(self):
        return self.updated_at

    def transactions(self):
        return self.transactions

