# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class Transaction(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.type = response_body['type']
        self.is_modified = response_body['is_modified']
        self.sender = response_body['sender']
        self.sender_account = response_body['sender_account']
        self.receiver = response_body['receiver']
        self.receiver_account = response_body['receiver_account']
        self.amount = response_body['amount']
        self.money_amount = response_body['money_amount']
        self.point_amount = response_body['point_amount']
        self.raw_point_amount = response_body['raw_point_amount']
        self.campaign_point_amount = response_body['campaign_point_amount']
        self.done_at = response_body['done_at']
        self.description = response_body['description']

    def id(self):
        return self.id

    def type(self):
        return self.type

    def is_modified(self):
        return self.is_modified

    def sender(self):
        return self.sender

    def sender_account(self):
        return self.sender_account

    def receiver(self):
        return self.receiver

    def receiver_account(self):
        return self.receiver_account

    def amount(self):
        return self.amount

    def money_amount(self):
        return self.money_amount

    def point_amount(self):
        return self.point_amount

    def raw_point_amount(self):
        return self.raw_point_amount

    def campaign_point_amount(self):
        return self.campaign_point_amount

    def done_at(self):
        return self.done_at

    def description(self):
        return self.description

