# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class Transfer(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.sender_account = response_body['sender_account']
        self.receiver_account = response_body['receiver_account']
        self.amount = response_body['amount']
        self.money_amount = response_body['money_amount']
        self.point_amount = response_body['point_amount']
        self.done_at = response_body['done_at']
        self.type = response_body['type']
        self.description = response_body['description']
        self.transaction_id = response_body['transaction_id']

    def id(self):
        return self.id

    def sender_account(self):
        return self.sender_account

    def receiver_account(self):
        return self.receiver_account

    def amount(self):
        return self.amount

    def money_amount(self):
        return self.money_amount

    def point_amount(self):
        return self.point_amount

    def done_at(self):
        return self.done_at

    def type(self):
        return self.type

    def description(self):
        return self.description

    def transaction_id(self):
        return self.transaction_id

