# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class UserStatsOperation(PokepayResponse):

    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.start = response_body['from']
        self.to = response_body['to']
        self.status = response_body['status']
        self.error_reason = response_body['error_reason']
        self.done_at = response_body['done_at']
        self.file_url = response_body['file_url']
        self.requested_at = response_body['requested_at']

    def id(self):
        return self.id

    def start(self):
        return self.start

    def to(self):
        return self.to

    def status(self):
        return self.status

    def error_reason(self):
        return self.error_reason

    def done_at(self):
        return self.done_at

    def file_url(self):
        return self.file_url

    def requested_at(self):
        return self.requested_at
