# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class UserTransaction(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.user = response_body['user']
        self.balance = response_body['balance']
        self.amount = response_body['amount']
        self.money_amount = response_body['money_amount']
        self.point_amount = response_body['point_amount']
        self.account = response_body['account']
        self.description = response_body['description']
        self.done_at = response_body['done_at']
        self.type = response_body['type']
        self.is_modified = response_body['is_modified']

    def id(self):
        return self.id

    def user(self):
        return self.user

    def balance(self):
        return self.balance

    def amount(self):
        return self.amount

    def money_amount(self):
        return self.money_amount

    def point_amount(self):
        return self.point_amount

    def account(self):
        return self.account

    def description(self):
        return self.description

    def done_at(self):
        return self.done_at

    def type(self):
        return self.type

    def is_modified(self):
        return self.is_modified

