# DO NOT EDIT: File is generated by code generator.

from pokepay.response.response import PokepayResponse


class UserCard(PokepayResponse):
    def __init__(self, response, response_body):
        super().__init__(response, response_body)
        self.id = response_body['id']
        self.card_number = response_body['card_number']
        self.registered_at = response_body['registered_at']

    def id(self):
        return self.id

    def card_number(self):
        return self.card_number

    def registered_at(self):
        return self.registered_at

