// DO NOT EDIT: File is generated by code generator.

import { AccountTransferSummaryElement } from "./AccountTransferSummaryElement";

interface AccountTransferSummary {
  readonly summaries: AccountTransferSummaryElement[];
}

export { AccountTransferSummary };
