// DO NOT EDIT: File is generated by code generator.

interface AccountBalance {
  readonly expires_at: string;
  readonly money_amount: number;
  readonly point_amount: number;
}

export { AccountBalance };
