// DO NOT EDIT: File is generated by code generator.

interface AccountTransferSummaryElement {
  readonly transfer_type: string;
  readonly money_amount: number;
  readonly point_amount: number;
  readonly count: number;
}

export { AccountTransferSummaryElement };
