// DO NOT EDIT: File is generated by code generator.

import { PrivateMoney } from "./PrivateMoney";

interface Bank {
  readonly id: string;
  readonly private_money: PrivateMoney;
  readonly bank_name: string;
  readonly bank_code: string;
  readonly branch_number: string;
  readonly branch_name: string;
  readonly deposit_type: string;
  readonly masked_account_number: string;
  readonly account_name: string;
}

export { Bank };
