// DO NOT EDIT: File is generated by code generator.

import { User } from "./User";
import { Account } from "./Account";
import { TransactionDetail } from "./TransactionDetail";

interface ExternalTransactionDetail {
  readonly id: string;
  readonly is_modified: boolean;
  readonly sender: User;
  readonly sender_account: Account;
  readonly receiver: User;
  readonly receiver_account: Account;
  readonly amount: number;
  readonly done_at: string;
  readonly description: string;
  readonly transaction?: TransactionDetail;
}

export { ExternalTransactionDetail };
