// DO NOT EDIT: File is generated by code generator.

interface OrganizationSummary {
  readonly count: number;
  readonly money_amount: number;
  readonly money_count: number;
  readonly point_amount: number;
  readonly raw_point_amount: number;
  readonly campaign_point_amount: number;
  readonly point_count: number;
}

export { OrganizationSummary };
