// DO NOT EDIT: File is generated by code generator.

import { Organization } from "./Organization";
import { Pagination } from "./Pagination";

interface PaginatedOrganizations {
  readonly rows: Organization[];
  readonly count: number;
  readonly pagination: Pagination;
}

export { PaginatedOrganizations };
