// DO NOT EDIT: File is generated by code generator.

import { Check } from "./Check";
import { Pagination } from "./Pagination";

interface PaginatedChecks {
  readonly rows: Check[];
  readonly count: number;
  readonly pagination: Pagination;
}

export { PaginatedChecks };
