// DO NOT EDIT: File is generated by code generator.

import { AccountWithUser } from "./AccountWithUser";
import { Pagination } from "./Pagination";

interface PaginatedAccountWithUsers {
  readonly rows: AccountWithUser[];
  readonly count: number;
  readonly pagination: Pagination;
}

export { PaginatedAccountWithUsers };
