// DO NOT EDIT: File is generated by code generator.

import { Organization } from "./Organization";

interface PrivateMoney {
  readonly id: string;
  readonly name: string;
  readonly unit: string;
  readonly is_exclusive: boolean;
  readonly description: string;
  readonly oneline_message: string;
  readonly organization: Organization;
  readonly max_balance: number;
  readonly transfer_limit: number;
  readonly money_topup_transfer_limit: number;
  readonly type: string;
  readonly expiration_type: string;
  readonly enable_topup_by_member?: boolean;
  readonly display_money_and_point: string;
}

export { PrivateMoney };
