// DO NOT EDIT: File is generated by code generator.

interface Product {
  readonly jan_code: string;
  readonly name: string;
  readonly unit_price: number;
  readonly price: number;
  readonly quantity?: number;
  readonly is_discounted: boolean;
  readonly other: string;
}

export { Product };
