// DO NOT EDIT: File is generated by code generator.

interface ShopWithMetadata {
  readonly id: string;
  readonly name: string;
  readonly organization_code: string;
  readonly status: string;
  readonly postal_code?: string;
  readonly address?: string;
  readonly tel?: string;
  readonly email?: string;
  readonly external_id?: string;
}

export { ShopWithMetadata };
