// DO NOT EDIT: File is generated by code generator.

import { User } from "./User";

interface UserDevice {
  readonly id: string;
  readonly user: User;
  readonly is_active: boolean;
  readonly metadata: string;
}

export { UserDevice };
