// DO NOT EDIT: File is generated by code generator.

interface UserStatsOperationServiceUnavailable {
  readonly type: string;
  readonly message: string;
}

export { UserStatsOperationServiceUnavailable };
