# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.bulk_transaction import BulkTransaction


class BulkCreateTransaction(PokepayRequest):
    def __init__(self, message):
        self.path = "/transactions" + "/bulk"
        self.method = "POST"
        self.body_params = {"name": name,
                            "content": content,
                            "request_id": request_id}
        self.response_class = BulkTransaction
