# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.bulk_transaction import BulkTransaction


class BulkCreateTransaction(PokepayRequest):
    def __init__(self, name, content, request_id, **rest_args):
        self.path = "/transactions" + "/bulk"
        self.method = "POST"
        self.body_params = {"name": name,
                            "content": content,
                            "request_id": request_id}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = BulkTransaction
