# DO NOT EDIT: File is generated by code generator.

from pokepay_partner_python_sdk.pokepay.request.request import PokepayRequest
from pokepay_partner_python_sdk.pokepay.response.bulk_transaction import BulkTransaction


class BulkCreateTransaction(PokepayRequest):
    def __init__(self, name, content, request_id, **rest_args):
        self.path = "/transactions" + "/bulk"
        self.method = "POST"
        self.body_params = {"name": name,
                            "content": content,
                            "request_id": request_id}
        self.body_params.update(rest_args)
        self.response_class = BulkTransaction
