# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.captured_credit_session import CapturedCreditSession


class CaptureCreditSession(PokepayRequest):
    def __init__(self, session_id, **rest_args):
        self.path = "/credit-sessions" + "/" + session_id + "/capture"
        self.method = "POST"
        self.body_params = {}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = CapturedCreditSession
