# DO NOT EDIT: File is generated by code generator.

from pokepay_partner_python_sdk.pokepay.request.request import PokepayRequest
from pokepay_partner_python_sdk.pokepay.response.organization import Organization


class CreateOrganization(PokepayRequest):
    def __init__(self, code, name, private_money_ids, issuer_admin_user_email, member_admin_user_email, **rest_args):
        self.path = "/organizations"
        self.method = "POST"
        self.body_params = {"code": code,
                            "name": name,
                            "private_money_ids": private_money_ids,
                            "issuer_admin_user_email": issuer_admin_user_email,
                            "member_admin_user_email": member_admin_user_email}
        self.body_params.update(rest_args)
        self.response_class = Organization
