# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.user_card import UserCard


class CreateCustomerCard(PokepayRequest):
    def __init__(self, customer_id, token, **rest_args):
        self.path = "/customers" + "/" + customer_id + "/cards"
        self.method = "POST"
        self.body_params = {"token": token}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = UserCard
