# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.user import User


class CreateShop(PokepayRequest):
    def __init__(self, shop_name, **rest_args):
        self.path = "/shops"
        self.method = "POST"
        self.body_params = {"shop_name": shop_name}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = User
