# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.user import User


class CreateShop(PokepayRequest):
    def __init__(self, message):
        self.path = "/shops"
        self.method = "POST"
        self.body_params = {"shop_name": shop_name}
        self.response_class = User
