# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.check import Check


class CreateCheck(PokepayRequest):
    def __init__(self, message):
        self.path = "/checks"
        self.method = "POST"
        self.body_params = {"account_id": account_id}
        self.response_class = Check
