# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.credit_session_transaction_result import CreditSessionTransactionResult


class CreateCreditSessionTransaction(PokepayRequest):
    def __init__(self, session_id, amount, **rest_args):
        self.path = "/credit-sessions" + "/" + session_id + "/transactions"
        self.method = "POST"
        self.body_params = {"amount": amount}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = CreditSessionTransactionResult
