# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.cvs_authorization import CvsAuthorization


class CreateCvsAuthorization(PokepayRequest):
    def __init__(self, customer_id, private_money_id, amount, service_option_type, name1, name2, tel, **rest_args):
        self.path = "/cvs"
        self.method = "POST"
        self.body_params = {"customer_id": customer_id,
                            "private_money_id": private_money_id,
                            "amount": amount,
                            "service_option_type": service_option_type,
                            "name1": name1,
                            "name2": name2,
                            "tel": tel}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = CvsAuthorization
