# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.cashtray import Cashtray


class CreateCashtray(PokepayRequest):
    def __init__(self, private_money_id, shop_id, amount, **rest_args):
        self.path = "/cashtrays"
        self.method = "POST"
        self.body_params = {"private_money_id": private_money_id,
                            "shop_id": shop_id,
                            "amount": amount}
        self.body_params.update(rest_args)
        self.response_class = Cashtray
