# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.transaction import Transaction


class CreateTopupTransactionWithCheck(PokepayRequest):
    def __init__(self, message):
        self.path = "/transactions" + "/topup" + "/check"
        self.method = "POST"
        self.body_params = {"check_id": check_id,
                            "customer_id": customer_id}
        self.response_class = Transaction
