# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.shop_with_accounts import ShopWithAccounts


class CreateShopV2(PokepayRequest):
    def __init__(self, message):
        self.path = "/shops-v2"
        self.method = "POST"
        self.body_params = {"name": name}
        self.response_class = ShopWithAccounts
