# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.transaction_detail import TransactionDetail


class CreateCpmTransaction(PokepayRequest):
    def __init__(self, cpm_token, shop_id, amount, **rest_args):
        self.path = "/transactions" + "/cpm"
        self.method = "POST"
        self.body_params = {"cpm_token": cpm_token,
                            "shop_id": shop_id,
                            "amount": amount}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = TransactionDetail
