# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.cashtray import Cashtray


class CreateCashtray(PokepayRequest):
    def __init__(self, message):
        self.path = "/cashtrays"
        self.method = "POST"
        self.body_params = {"private_money_id": private_money_id,
                            "shop_id": shop_id,
                            "amount": amount}
        self.response_class = Cashtray
