# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.organization import Organization


class CreateOrganization(PokepayRequest):
    def __init__(self, message):
        self.path = "/organizations"
        self.method = "POST"
        self.body_params = {"code": code,
                            "name": name,
                            "private_money_ids": private_money_ids,
                            "issuer_admin_user_email": issuer_admin_user_email,
                            "member_admin_user_email": member_admin_user_email}
        self.response_class = Organization
