# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.organization import Organization


class CreateOrganization(PokepayRequest):
    def __init__(self, code, name, private_money_ids, issuer_admin_user_email, member_admin_user_email, **rest_args):
        self.path = "/organizations"
        self.method = "POST"
        self.body_params = {"code": code,
                            "name": name,
                            "private_money_ids": private_money_ids,
                            "issuer_admin_user_email": issuer_admin_user_email,
                            "member_admin_user_email": member_admin_user_email}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = Organization
