# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.user_device import UserDevice


class CreateUserDevice(PokepayRequest):
    def __init__(self, user_id, **rest_args):
        self.path = "/user-devices"
        self.method = "POST"
        self.body_params = {"user_id": user_id}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = UserDevice
