# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.transaction_group import TransactionGroup


class CreateTransactionGroup(PokepayRequest):
    def __init__(self, name):
        self.path = "/transaction-groups"
        self.method = "POST"
        self.body_params = {"name": name}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = TransactionGroup
