# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.transaction import Transaction


class CreateTransaction(PokepayRequest):
    def __init__(self, message):
        self.path = "/transactions"
        self.method = "POST"
        self.body_params = {"shop_id": shop_id,
                            "customer_id": customer_id,
                            "private_money_id": private_money_id}
        self.response_class = Transaction
