# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.check import Check


class CreateCheck(PokepayRequest):
    def __init__(self, account_id, **rest_args):
        self.path = "/checks"
        self.method = "POST"
        self.body_params = {"account_id": account_id}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = Check
