# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.coupon_detail import CouponDetail


class CreateCoupon(PokepayRequest):
    def __init__(self, private_money_id, name, starts_at, ends_at, issued_shop_id, **rest_args):
        self.path = "/coupons"
        self.method = "POST"
        self.body_params = {"private_money_id": private_money_id,
                            "name": name,
                            "starts_at": starts_at,
                            "ends_at": ends_at,
                            "issued_shop_id": issued_shop_id}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = CouponDetail
