# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.transaction import Transaction


class CreateTransferTransaction(PokepayRequest):
    def __init__(self, message):
        self.path = "/transactions" + "/transfer"
        self.method = "POST"
        self.body_params = {"sender_id": sender_id,
                            "receiver_id": receiver_id,
                            "private_money_id": private_money_id,
                            "amount": amount}
        self.response_class = Transaction
