# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.shop_with_accounts import ShopWithAccounts


class CreateShopV2(PokepayRequest):
    def __init__(self, name, **rest_args):
        self.path = "/shops-v2"
        self.method = "POST"
        self.body_params = {"name": name}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = ShopWithAccounts
