# DO NOT EDIT: File is generated by code generator.

from pokepay_partner_python_sdk.pokepay.request.request import PokepayRequest
from pokepay_partner_python_sdk.pokepay.response.account_detail import AccountDetail


class CreateUserAccount(PokepayRequest):
    def __init__(self, user_id, private_money_id, **rest_args):
        self.path = "/users" + "/" + user_id + "/accounts"
        self.method = "POST"
        self.body_params = {"private_money_id": private_money_id}
        self.body_params.update(rest_args)
        self.response_class = AccountDetail
