# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.transaction_detail import TransactionDetail


class CreateTransferTransaction(PokepayRequest):
    def __init__(self, sender_id, receiver_id, private_money_id, amount, **rest_args):
        self.path = "/transactions" + "/transfer"
        self.method = "POST"
        self.body_params = {"sender_id": sender_id,
                            "receiver_id": receiver_id,
                            "private_money_id": private_money_id,
                            "amount": amount}
        self.body_params.update(rest_args)
        self.response_class = TransactionDetail
