# DO NOT EDIT: File is generated by code generator.

from pokepay_partner_python_sdk.pokepay.request.request import PokepayRequest
from pokepay_partner_python_sdk.pokepay.response.transaction_detail import TransactionDetail


class CreateTopupTransactionWithCheck(PokepayRequest):
    def __init__(self, check_id, customer_id):
        self.path = "/transactions" + "/topup" + "/check"
        self.method = "POST"
        self.body_params = {"check_id": check_id,
                            "customer_id": customer_id}
        
        self.response_class = TransactionDetail
