# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.card_authorize_result import CardAuthorizeResult


class CreditCardTopupWithMdkToken(PokepayRequest):
    def __init__(self, customer_id, token, private_money_id, amount, **rest_args):
        self.path = "/customers" + "/" + customer_id + "/card-authorize" + "/topup-with-mdk-token"
        self.method = "POST"
        self.body_params = {"token": token,
                            "private_money_id": private_money_id,
                            "amount": amount}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = CardAuthorizeResult
