# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.organization_worker_task_webhook import OrganizationWorkerTaskWebhook


class DeleteWebhook(PokepayRequest):
    def __init__(self, webhook_id):
        self.path = "/webhooks" + "/" + webhook_id
        self.method = "DELETE"
        self.body_params = {}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = OrganizationWorkerTaskWebhook
