# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.customer_card_deleted import CustomerCardDeleted


class DeleteCustomerCard(PokepayRequest):
    def __init__(self, customer_id, card_uuid):
        self.path = "/customers" + "/" + customer_id + "/cards" + "/delete"
        self.method = "POST"
        self.body_params = {"card_uuid": card_uuid}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = CustomerCardDeleted
