# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.bank_deleted import BankDeleted


class DeleteBank(PokepayRequest):
    def __init__(self, user_device_id, bank_id):
        self.path = "/user-devices" + "/" + user_device_id + "/banks"
        self.method = "DELETE"
        self.body_params = {"bank_id": bank_id}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = BankDeleted
