# DO NOT EDIT: File is generated by code generator.

from pokepay_partner_python_sdk.pokepay.request.request import PokepayRequest
from pokepay_partner_python_sdk.pokepay.response.private_money_summary import PrivateMoneySummary


class GetPrivateMoneySummary(PokepayRequest):
    def __init__(self, private_money_id, **rest_args):
        self.path = "/private-moneys" + "/" + private_money_id + "/summary"
        self.method = "GET"
        self.body_params = {}
        self.body_params.update(rest_args)
        self.response_class = PrivateMoneySummary
