# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.check import Check


class GetCheck(PokepayRequest):
    def __init__(self, check_id):
        self.path = "/checks" + "/" + check_id
        self.method = "GET"
        self.body_params = {}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = Check
