# DO NOT EDIT: File is generated by code generator.

from pokepay_partner_python_sdk.pokepay.request.request import PokepayRequest
from pokepay_partner_python_sdk.pokepay.response.cpm_token import CpmToken


class GetCpmToken(PokepayRequest):
    def __init__(self, cpm_token):
        self.path = "/cpm" + "/" + cpm_token
        self.method = "GET"
        self.body_params = {}
        
        self.response_class = CpmToken
