# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_user_cards import PaginatedUserCards


class GetCustomerCards(PokepayRequest):
    def __init__(self, customer_id, **rest_args):
        self.path = "/customers" + "/" + customer_id + "/cards"
        self.method = "GET"
        self.body_params = {}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = PaginatedUserCards
