# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_private_money_organization_summaries import PaginatedPrivateMoneyOrganizationSummaries


class GetPrivateMoneyOrganizationSummaries(PokepayRequest):
    def __init__(self, message):
        self.path = "/private-moneys" + "/" + private_money_id + "/organization-summaries"
        self.method = "GET"
        self.body_params = {}
        self.response_class = PaginatedPrivateMoneyOrganizationSummaries
