# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_account_with_users import PaginatedAccountWithUsers


class GetShopAccounts(PokepayRequest):
    def __init__(self, message):
        self.path = "/accounts" + "/shops"
        self.method = "GET"
        self.body_params = {"private_money_id": private_money_id}
        self.response_class = PaginatedAccountWithUsers
