# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.external_transaction_detail import ExternalTransactionDetail


class GetExternalTransactionByRequestId(PokepayRequest):
    def __init__(self, request_id):
        self.path = "/external-transactions" + "/requests" + "/" + request_id
        self.method = "GET"
        self.body_params = {}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = ExternalTransactionDetail
