# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.admin_user_with_shops_and_private_moneys import AdminUserWithShopsAndPrivateMoneys


class GetUser(PokepayRequest):
    def __init__(self, ):
        self.path = "/user"
        self.method = "GET"
        self.body_params = {}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = AdminUserWithShopsAndPrivateMoneys
