# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.bulk_transaction import BulkTransaction


class GetBulkTransaction(PokepayRequest):
    def __init__(self, message):
        self.path = "/bulk-transactions" + "/" + bulk_transaction_id
        self.method = "GET"
        self.body_params = {}
        self.response_class = BulkTransaction
