# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.seven_bank_atm_session import SevenBankATMSession


class GetSevenBankATMSession(PokepayRequest):
    def __init__(self, qr_info):
        self.path = "/seven-bank-atm-sessions" + "/" + qr_info
        self.method = "GET"
        self.body_params = {}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = SevenBankATMSession
