# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.coupon_detail import CouponDetail


class GetCoupon(PokepayRequest):
    def __init__(self, coupon_id):
        self.path = "/coupons" + "/" + coupon_id
        self.method = "GET"
        self.body_params = {}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = CouponDetail
