# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.campaign import Campaign


class GetCampaign(PokepayRequest):
    def __init__(self, campaign_id):
        self.path = "/campaigns" + "/" + campaign_id
        self.method = "GET"
        self.body_params = {}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = Campaign
