# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.bill_with_additional_private_moneys import BillWithAdditionalPrivateMoneys


class GetBill(PokepayRequest):
    def __init__(self, bill_id):
        self.path = "/bills" + "/" + bill_id
        self.method = "GET"
        self.body_params = {}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = BillWithAdditionalPrivateMoneys
