# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_private_money_organization_summaries import PaginatedPrivateMoneyOrganizationSummaries


class GetPrivateMoneyOrganizationSummaries(PokepayRequest):
    def __init__(self, private_money_id, **rest_args):
        self.path = "/private-moneys" + "/" + private_money_id + "/organization-summaries"
        self.method = "GET"
        self.body_params = {}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = PaginatedPrivateMoneyOrganizationSummaries
