# DO NOT EDIT: File is generated by code generator.

from pokepay_partner_python_sdk.pokepay.request.request import PokepayRequest
from pokepay_partner_python_sdk.pokepay.response.admin_user_with_shops_and_private_moneys import AdminUserWithShopsAndPrivateMoneys


class GetUser(PokepayRequest):
    def __init__(self, ):
        self.path = "/user"
        self.method = "GET"
        self.body_params = {}
        
        self.response_class = AdminUserWithShopsAndPrivateMoneys
