# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.bulk_transaction import BulkTransaction


class GetBulkTransaction(PokepayRequest):
    def __init__(self, bulk_transaction_id):
        self.path = "/bulk-transactions" + "/" + bulk_transaction_id
        self.method = "GET"
        self.body_params = {}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = BulkTransaction
