# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.cvs_authorization import CvsAuthorization


class GetCvsAuthorization(PokepayRequest):
    def __init__(self, order_id):
        self.path = "/cvs" + "/" + order_id
        self.method = "GET"
        self.body_params = {}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = CvsAuthorization
