# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_private_moneys import PaginatedPrivateMoneys


class GetPrivateMoneys(PokepayRequest):
    def __init__(self, message):
        self.path = "/private-moneys"
        self.method = "GET"
        self.body_params = {}
        self.response_class = PaginatedPrivateMoneys
