# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_campaigns import PaginatedCampaigns


class ListCampaigns(PokepayRequest):
    def __init__(self, private_money_id, **rest_args):
        self.path = "/campaigns"
        self.method = "GET"
        self.body_params = {"private_money_id": private_money_id}
        self.body_params.update(rest_args)
        self.response_class = PaginatedCampaigns
