# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_shops import PaginatedShops


class ListShops(PokepayRequest):
    def __init__(self, message):
        self.path = "/shops"
        self.method = "GET"
        self.body_params = {}
        self.response_class = PaginatedShops
