# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_transfers import PaginatedTransfers


class ListTransfers(PokepayRequest):
    def __init__(self, message):
        self.path = "/transfers"
        self.method = "GET"
        self.body_params = {}
        self.response_class = PaginatedTransfers
