# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_transaction import PaginatedTransaction


class ListTransactions(PokepayRequest):
    def __init__(self, message):
        self.path = "/transactions"
        self.method = "GET"
        self.body_params = {}
        self.response_class = PaginatedTransaction
