# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_account_balance import PaginatedAccountBalance


class ListAccountBalances(PokepayRequest):
    def __init__(self, account_id, **rest_args):
        self.path = "/accounts" + "/" + account_id + "/balances"
        self.method = "GET"
        self.body_params = {}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = PaginatedAccountBalance
