# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_account_balance import PaginatedAccountBalance


class ListAccountExpiredBalances(PokepayRequest):
    def __init__(self, message):
        self.path = "/accounts" + "/" + account_id + "/expired-balances"
        self.method = "GET"
        self.body_params = {}
        self.response_class = PaginatedAccountBalance
