# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_organization_worker_task_webhook import PaginatedOrganizationWorkerTaskWebhook


class ListWebhooks(PokepayRequest):
    def __init__(self, **rest_args):
        self.path = "/webhooks"
        self.method = "GET"
        self.body_params = {}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = PaginatedOrganizationWorkerTaskWebhook
