# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_bills import PaginatedBills


class ListBills(PokepayRequest):
    def __init__(self, message):
        self.path = "/bills"
        self.method = "GET"
        self.body_params = {}
        self.response_class = PaginatedBills
