# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.banks import Banks


class ListBanks(PokepayRequest):
    def __init__(self, user_device_id, **rest_args):
        self.path = "/user-devices" + "/" + user_device_id + "/banks"
        self.method = "GET"
        self.body_params = {}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = Banks
