# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_coupons import PaginatedCoupons


class ListCoupons(PokepayRequest):
    def __init__(self, private_money_id, **rest_args):
        self.path = "/coupons"
        self.method = "GET"
        self.body_params = {"private_money_id": private_money_id}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = PaginatedCoupons
