# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_transaction import PaginatedTransaction


class ListCustomerTransactions(PokepayRequest):
    def __init__(self, message):
        self.path = "/customers" + "/transactions"
        self.method = "GET"
        self.body_params = {"private_money_id": private_money_id}
        self.response_class = PaginatedTransaction
