# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.paginated_bulk_transaction_job import PaginatedBulkTransactionJob


class ListBulkTransactionJobs(PokepayRequest):
    def __init__(self, bulk_transaction_id, **rest_args):
        self.path = "/bulk-transactions" + "/" + bulk_transaction_id + "/jobs"
        self.method = "GET"
        self.body_params = {}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = PaginatedBulkTransactionJob
