# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.credit_session import CreditSession


class PostCreditSession(PokepayRequest):
    def __init__(self, customer_id, private_money_id, card_id, expires_at, **rest_args):
        self.path = "/credit-sessions"
        self.method = "POST"
        self.body_params = {"customer_id": customer_id,
                            "private_money_id": private_money_id,
                            "card_id": card_id,
                            "expires_at": expires_at}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = CreditSession
