# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.transaction_detail import TransactionDetail


class RefundTransaction(PokepayRequest):
    def __init__(self, transaction_id, **rest_args):
        self.path = "/transactions" + "/" + transaction_id + "/refund"
        self.method = "POST"
        self.body_params = {}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = TransactionDetail
