# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.external_transaction import ExternalTransaction


class RefundExternalTransaction(PokepayRequest):
    def __init__(self, event_id, **rest_args):
        self.path = "/external-transactions" + "/" + event_id + "/refund"
        self.method = "POST"
        self.body_params = {}
        self.body_params.update(rest_args)
        self.response_class = ExternalTransaction
