# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.external_transaction_detail import ExternalTransactionDetail


class RefundExternalTransaction(PokepayRequest):
    def __init__(self, event_id, **rest_args):
        self.path = "/external-transactions" + "/" + event_id + "/refund"
        self.method = "POST"
        self.body_params = {}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = ExternalTransactionDetail
