# DO NOT EDIT: File is generated by code generator.

from pokepay_partner_python_sdk.pokepay.request.request import PokepayRequest
from pokepay_partner_python_sdk.pokepay.response.transaction_detail import TransactionDetail


class RefundTransaction(PokepayRequest):
    def __init__(self, transaction_id, **rest_args):
        self.path = "/transactions" + "/" + transaction_id + "/refund"
        self.method = "POST"
        self.body_params = {}
        self.body_params.update(rest_args)
        self.response_class = TransactionDetail
