# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.transaction import Transaction


class RefundTransaction(PokepayRequest):
    def __init__(self, message):
        self.path = "/transactions" + "/" + transaction_id + "/refund"
        self.method = "POST"
        self.body_params = {}
        self.response_class = Transaction
