# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.user_stats_operation import UserStatsOperation


class RequestUserStats(PokepayRequest):
    def __init__(self, start, to):
        self.path = "/user-stats"
        self.method = "POST"
        self.body_params = {"from": start,
                            "to": to}
        
        self.response_class = UserStatsOperation
