# DO NOT EDIT: File is generated by code generator.

from pokepay_partner_python_sdk.pokepay.request.request import PokepayRequest
from pokepay_partner_python_sdk.pokepay.response.echo import Echo


class SendEcho(PokepayRequest):
    def __init__(self, message):
        self.path = "/echo"
        self.method = "POST"
        self.body_params = {"message": message}
        
        self.response_class = Echo
