# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.transaction_group import TransactionGroup


class ShowTransactionGroup(PokepayRequest):
    def __init__(self, uuid):
        self.path = "/transaction-groups" + "/" + uuid
        self.method = "GET"
        self.body_params = {}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = TransactionGroup
