# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.user_stats_operation import UserStatsOperation


class TerminateUserStats(PokepayRequest):
    def __init__(self, operation_id):
        self.path = "/user-stats" + "/terminate"
        self.method = "POST"
        self.body_params = {"operation_id": operation_id}
        
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = UserStatsOperation
