# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.bill import Bill


class UpdateBill(PokepayRequest):
    def __init__(self, bill_id, **rest_args):
        self.path = "/bills" + "/" + bill_id
        self.method = "PATCH"
        self.body_params = {}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = Bill
