# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.account_detail import AccountDetail


class UpdateAccount(PokepayRequest):
    def __init__(self, message):
        self.path = "/accounts" + "/" + account_id
        self.method = "PATCH"
        self.body_params = {}
        self.response_class = AccountDetail
