# DO NOT EDIT: File is generated by code generator.

from pokepay_partner_python_sdk.pokepay.request.request import PokepayRequest
from pokepay_partner_python_sdk.pokepay.response.cashtray import Cashtray


class UpdateCashtray(PokepayRequest):
    def __init__(self, cashtray_id, **rest_args):
        self.path = "/cashtrays" + "/" + cashtray_id
        self.method = "PATCH"
        self.body_params = {}
        self.body_params.update(rest_args)
        self.response_class = Cashtray
