# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.cashtray import Cashtray


class UpdateCashtray(PokepayRequest):
    def __init__(self, cashtray_id, **rest_args):
        self.path = "/cashtrays" + "/" + cashtray_id
        self.method = "PATCH"
        self.body_params = {}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = Cashtray
