# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.shop_with_accounts import ShopWithAccounts


class UpdateShop(PokepayRequest):
    def __init__(self, shop_id, **rest_args):
        self.path = "/shops" + "/" + shop_id
        self.method = "PATCH"
        self.body_params = {}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = ShopWithAccounts
