# DO NOT EDIT: File is generated by code generator.

from pokepay.request.request import PokepayRequest
from pokepay.response.organization_worker_task_webhook import OrganizationWorkerTaskWebhook


class UpdateWebhook(PokepayRequest):
    def __init__(self, webhook_id, **rest_args):
        self.path = "/webhooks" + "/" + webhook_id
        self.method = "PATCH"
        self.body_params = {}
        self.body_params.update(rest_args)
        if 'start' in self.body_params:
            self.body_params['from'] = self.body_params.pop('start')
        self.response_class = OrganizationWorkerTaskWebhook
